# Generated by Django 4.2.16 on 2026-08-13 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('package_name', models.CharField(max_length=200)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('total_secs', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='families.family')),
            ],
            options={
                'ordering': ['-date', '-total_secs'],
                'indexes': [models.Index(fields=['child', 'date'], name='app_control_child_i_5639e5_idx')],
                'unique_together': {('child', 'date', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=200)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('is_blocked', models.BooleanField(default=False)),
                ('daily_limit_mins', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to='families.family')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_label'],
                'unique_together': {('family', 'child', 'package_name')},
            },
        ),
    ]
